FROM node:16

ARG CONFIG
ENV CONFIG=$CONFIG
ARG FIREBASE_SERVICE_ACCOUNT
ENV FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT

WORKDIR /usr/src/bot

COPY package*.json tsconfig.json ./
COPY src ./src

RUN npm ci

CMD ["npm","start"]
